In [ ]:
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

# Parameters
sns.set_theme(style="whitegrid")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [8]:
DATA_PATH = Path("../data/processed/noah_regional_dengue_master.csv")

df_raw = pd.read_csv(DATA_PATH)

print(f"Dataset shape: {df_raw.shape[0]:,} rows × {df_raw.shape[1]} columns")

display(df_raw.head())

Dataset shape: 7,072 rows × 9 columns

,region,year,week,dengue_cases,rainfall_estimate,temperature_era5,specific_humidity_era5,rainfall_approximated_flag,plausibility_flag
0,BARMM,2016,1,28,7.45,24.800019,16.393187,1,0
1,BARMM,2016,2,32,6.25,24.898520,16.865840,1,0
2,BARMM,2016,3,30,3.45,25.131403,15.779174,1,0
3,BARMM,2016,4,36,4.27,24.902053,15.019548,1,0
4,BARMM,2016,5,27,4.88,25.511344,15.852063,1,0

In [9]:
print("Column names:")
print(df_raw.columns.tolist())

print("\nData types:")
df_raw.info()

print("\nSummary statistics:")
display(df_raw.describe(include="all").T)

Column names:
['region', 'year', 'week', 'dengue_cases', 'rainfall_estimate', 'temperature_era5', 'specific_humidity_era5', 'rainfall_approximated_flag', 'plausibility_flag']

Data types:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7072 entries, 0 to 7071
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   region                      7072 non-null   object
 1   year                        7072 non-null   int64
 2   week                        7072 non-null   int64
 3   dengue_cases                7072 non-null   int64
 4   rainfall_estimate           7072 non-null   float64
 5   temperature_era5            7072 non-null   float64
 6   specific_humidity_era5      7072 non-null   float64
 7   rainfall_approximated_flag  7072 non-null   int64
 8   plausibility_flag           7072 non-null   int64
dtypes: float64(3), int64(5), object(1)
memory usage: 497.4+ KB

Summary statistics:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
region,7072,17,BARMM,416,NaN,NaN,NaN,NaN,NaN,NaN,NaN
year,7072.0,NaN,NaN,NaN,2020.5,3.201788,2016.0,2017.75,2020.5,2023.25,2025.0
week,7072.0,NaN,NaN,NaN,26.5,15.009392,1.0,13.75,26.5,39.25,52.0
dengue_cases,7072.0,NaN,NaN,NaN,307.404695,390.444437,1.0,87.0,183.0,364.0,4868.0
rainfall_estimate,7072.0,NaN,NaN,NaN,53.044094,41.251621,0.69,21.32,46.34,73.83,343.72
temperature_era5,7072.0,NaN,NaN,NaN,25.179037,1.48896,16.349712,24.412658,25.302357,26.089084,31.118581
specific_humidity_era5,7072.0,NaN,NaN,NaN,17.331286,1.349383,10.283531,16.656955,17.562463,18.314884,20.167817
rainfall_approximated_flag,7072.0,NaN,NaN,NaN,1.0,0.0,1.0,1.0,1.0,1.0,1.0
plausibility_flag,7072.0,NaN,NaN,NaN,0.000848,0.029117,0.0,0.0,0.0,0.0,1.0